services:
  - type: web
    name: coding-life
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*  
        destination: /index.html
    headers:
      - path: /videos/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    publicPath: /